import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
    ],
    safelist: [
        'opacity-80',
        'pointer-events-none',
        'animate-spin',
        'bg-red-600',
        'hover:bg-red-700',
        'focus:ring-red-100',
        'min-w-[120px]',
    ],
    theme: {
        extend: {
            colors: {
                'on-secondary-fixed': '#140f54',
                'on-tertiary-container': '#ffd2be',
                'error-container': '#ffdad6',
                'inverse-on-surface': '#eff1f3',
                tertiary: '#7e3000',
                'primary-container': '#4f46e5',
                'on-tertiary-fixed': '#351000',
                'on-primary-fixed-variant': '#3323cc',
                'inverse-primary': '#c3c0ff',
                'on-secondary-fixed-variant': '#413f82',
                'on-surface-variant': '#464555',
                'inverse-surface': '#2d3133',
                'tertiary-container': '#a44100',
                'on-surface': '#191c1e',
                'surface-dim': '#d8dadc',
                surface: '#f7f9fb',
                secondary: '#58579b',
                'on-background': '#191c1e',
                primary: '#3525cd',
                'surface-tint': '#4d44e3',
                'on-error': '#ffffff',
                'surface-bright': '#f7f9fb',
                'tertiary-fixed-dim': '#ffb695',
                'on-primary-fixed': '#0f0069',
                'primary-fixed-dim': '#c3c0ff',
                'secondary-fixed-dim': '#c3c0ff',
                'surface-variant': '#e0e3e5',
                'surface-container-highest': '#e0e3e5',
                'on-error-container': '#93000a',
                'surface-container-low': '#f2f4f6',
                'on-tertiary-fixed-variant': '#7b2f00',
                outline: '#777587',
                'on-secondary': '#ffffff',
                'on-primary-container': '#dad7ff',
                'surface-container': '#eceef0',
                'primary-fixed': '#e2dfff',
                'on-primary': '#ffffff',
                'surface-container-high': '#e6e8ea',
                error: '#ba1a1a',
                'outline-variant': '#c7c4d8',
                'on-tertiary': '#ffffff',
                'secondary-container': '#b6b4ff',
                'tertiary-fixed': '#ffdbcc',
                'surface-container-lowest': '#ffffff',
                'secondary-fixed': '#e2dfff',
                'on-secondary-container': '#454386',
                background: '#f7f9fb',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            fontFamily: {
                headline: ['Manrope', 'sans-serif'],
                body: ['Inter', 'sans-serif'],
                label: ['Inter', 'sans-serif'],
            },
        },
    },
    plugins: [forms, containerQueries],
};
